name: Build srcjs

on:
  schedule:
    - cron:  '0 7 14 * *'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: ['14']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Create pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Monthly update
          delete-branch: true